 'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabaseBrowser} from '../lib/supabase-browser';
import type {Product,CartItem} from '../lib/types';

const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' CFA';

export default function Shop(){
 const sb=supabaseBrowser(); const [products,setProducts]=useState<Product[]>([]); const [ownerPhone,setOwnerPhone]=useState('+223 78 30 98 51'); const [q,setQ]=useState(''); const [cart,setCart]=useState<CartItem[]>([]); const [open,setOpen]=useState(false); const [done,setDone]=useState(false);
 const [form,setForm]=useState({name:'',phone:'',zone:'',address:'',note:''});
 useEffect(()=>{Promise.all([sb.from('products').select('*').eq('active',true).order('created_at',{ascending:false}),sb.from('settings').select('value').eq('key','owner_phone').maybeSingle()]).then(([p,s])=>{setProducts(p.data||[]);if(s.data?.value)setOwnerPhone(s.data.value)})},[]);
 const filtered=useMemo(()=>products.filter(p=>(p.name+' '+p.description).toLowerCase().includes(q.toLowerCase())),[products,q]);
 const total=cart.reduce((s,x)=>s+x.product.price_cfa*x.quantity,0);
 function add(p:Product){setCart(c=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,quantity:Math.min(p.stock,i.quantity+1)}:i):[...c,{product:p,quantity:1}]});setOpen(true)}
 async function checkout(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:form,items:cart.map(x=>({product_id:x.product.id,quantity:x.quantity}))})});if(r.ok){setCart([]);setDone(true);setForm({name:'',phone:'',zone:'',address:'',note:''})}else alert(`Impossible d’enregistrer la commande. Réessayez.`)}
 return <>
 <header className="header"><a href="/"><img src="/logo.png" className="logo" alt="Drop & Roll"/></a><nav className="nav"><a href="#products">Produits</a><a href="#about">À propos</a><a href="#faq">FAQ</a><a className="admin-nav" href="/login">Admin</a><button className="btn light" onClick={()=>setOpen(true)}>Panier ({cart.reduce((s,x)=>s+x.quantity,0)})</button></nav></header>
 <section className="hero"><div><span className="eyebrow">DERMA SYSTEMS</span><h1>Une routine simple. Une boutique claire.</h1><p className="muted">Découvrez les produits Drop & Roll et commandez facilement avec paiement à la livraison.</p><a className="btn primary" href="#products">Voir les produits</a></div><img src="/logo.png" className="hero-logo" alt="Drop & Roll"/></section>
 <section id="products" className="container"><div className="section-head"><div><span className="eyebrow">CATALOGUE</span><h2>Nos produits</h2></div><input className="search" placeholder="Rechercher…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="product-img">{p.image_url?<img src={p.image_url} alt=""/>:<span>D&R</span>}</div><div className="card-body"><h3>{p.name}</h3><p className="muted">{p.description}</p><div className="price">{money(p.price_cfa)}</div><p className="muted">{p.stock>0?`En stock · ${p.stock}`:'Rupture de stock'}</p><button className="btn primary" disabled={!p.stock} onClick={()=>add(p)}>Ajouter au panier</button></div></article>)}</div></section>
 <section id="about" className="container"><span className="eyebrow">À PROPOS</span><h2>Drop & Roll</h2><p className="muted">Une boutique orientée vers une expérience d’achat simple, claire et rapide.</p></section>
 <section id="faq" className="container"><span className="eyebrow">FAQ</span><h2>Questions fréquentes</h2><div className="panel"><p><b>Comment payer ?</b><br/>Paiement à la livraison.</p><p><b>Comment est calculée la livraison ?</b><br/>Elle dépend de la zone et sera confirmée lors de la commande.</p></div></section>
 <footer className="footer"><div><b>Drop & Roll</b><p>Derma Systems</p></div><div><b>Contact</b><p><a href={'tel:'+ownerPhone.replace(/\s/g,'')}>{ownerPhone}</a></p></div></footer>
 {open&&<><div className="backdrop" onClick={()=>setOpen(false)}/><aside className="cart"><button className="btn light" onClick={()=>setOpen(false)}>Fermer</button><h2>Votre panier</h2>{done?<div><p>Commande enregistrée. Nous vous contacterons pour confirmer la livraison.</p><button className="btn light" onClick={()=>{setDone(false);setOpen(false);}}>Faire une nouvelle commande</button></div>:<>{cart.map(x=><div className="row" key={x.product.id}><div>{x.product.name}<br/><span className="muted">{money(x.product.price_cfa)} × {x.quantity}</span></div><div><button className="btn light" onClick={()=>setCart(c=>c.map(i=>i.product.id===x.product.id?{...i,quantity:Math.max(1,i.quantity-1)}:i))}>−</button> <button className="btn light" onClick={()=>add(x.product)}>+</button> <button className="btn light" style={{color:'#c73535'}} onClick={()=>setCart(c=>c.filter(i=>i.product.id!==x.product.id))}>✕</button></div></div>)}<h3>Total : {money(total)}</h3>{cart.length>0&&<form className="form" onSubmit={checkout}><label>Nom complet<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Téléphone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Ville / zone<input required value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})}/></label><label>Adresse<input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Note<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="btn primary">Confirmer — paiement à la livraison</button></form>}</>}</aside></>}
 </>}
